# %%
import random
marcas_carros =[
'CHEVROLET','VOLKSWAGEN','FIAT','MERCEDES-BENZ',
'CITROEN','HONDA','SUBARU','FERRARI',
'BUGATTI','LAMBORGHINI','FORD','HYUNDAI','JAC',
'KIA','GURGEL','DODGE','CHRYSLER','BENTLEY',
'PEUGEOT','TOYOTA','RENAULT',
'ALFA ROMEO','AUDI','BMW',
'NISSAN','CHAMONIX','CHERY',
'VOLVO','SUZUKI','EAGLE','PORSCHE',
'HUDSON','HUMMER','JAGUAR','JEEP','LAND ROVER','LEXUS',
'LOTUS','MERCURY','MITSUBISHI','PUMA']
# %%
