# %%
marcas_carros =[
'CHEVROLET','VOLKSWAGEN','FIAT','MERCEDES-BENZ',
'CITROEN','HONDA','SUBARU','FERRARI',
'BUGATTI','LAMBORGHINI','FORD','HYUNDAI','JAC',
'KIA','GURGEL','DODGE','CHRYSLER','BENTLEY',
'PEUGEOT','TOYOTA','RENAULT',
'ALFA ROMEO','AUDI','BMW',
'NISSAN','CHAMONIX','CHERY',
'VOLVO','SUZUKI','EAGLE','PORSCHE',
'HUDSON','HUMMER','JAGUAR','JEEP','LAND ROVER','LEXUS',
'LOTUS','MERCURY','MITSUBISHI','PUMA']
# %%
produtos = [
'Filtro ou purificador',
'Potes de vidro',
'Formas e assadeiras',
'Colher de pau',
'Açucareiro',
'Saleiro',
'Mantegueira',
'Saca-rolhas',
'Abridor de latas',
'Formas de gelo',
'Panos de prato',
'Pano de pia',
'Rodo de pia',
'Lixeira',
'Escorredor de louça',
'Esponja',
'Tesoura',
'Ralador de queijo',
'Tábua de corte',
'Escorredor de macarrão',
'Pegador de massa',
'Peneira',
'Escumadeira',
'Garrafa térmica',
'Cafeteira',
'Torradeira',
'Espremedor',
'Papel-toalha',
'Copo de medidas',
'Jogo americano',
'Cabides',
'Colchão',
'Capa protetora para colchão',
'Travesseiro',
'Fronhas',
'Lençol',
'Edredom',
'Ventilador',
'Sapateira',
'Toalha de rosto',
'Toalha de banho',
'Lixeira',
'Tapete de banheiro',
'Escova sanitária',
'Porta escova de dentes',
'Saboneteira',
'Sabonetes extras',
'Cadeiras',
'Almofadas',
'Tapete',
'TV ',
'Rack',
]
# %%
